log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: mail@example.com
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-router:
      rule: "Host(`bookwormtest.pennds.org`)"
      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: bookworm

    web-secure-router:
      rule: "Host(`bookwormtest.pennds.org`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: bookworm
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt
        domains:
          - main: "bookwormtest.pennds.org"
            sans:
              - "*.bookwormtest.pennds.org"

  middlewares:
    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    bookworm:
      loadBalancer:
        servers:
          - url: http://bookworm:10012

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yaml
    watch: true
